[2022-02-24 20:01:44,012] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T14:00:00+00:00 [queued]>
[2022-02-24 20:01:44,756] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T14:00:00+00:00 [queued]>
[2022-02-24 20:01:44,759] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:44,762] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:01:44,768] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:45,028] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_reddit_data> on 2022-02-24 14:00:00+00:00
[2022-02-24 20:01:45,074] {standard_task_runner.py:52} INFO - Started process 673 to run task
[2022-02-24 20:01:45,147] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'get_reddit_data', 'scheduled__2022-02-24T14:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpcit994cu', '--error-file', '/tmp/tmproqxqmd0']
[2022-02-24 20:01:45,167] {standard_task_runner.py:77} INFO - Job 47: Subtask get_reddit_data
[2022-02-24 20:01:46,772] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T14:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 20:01:48,733] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=get_reddit_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T14:00:00+00:00
[2022-02-24 20:52:24,043] {logging_mixin.py:109} INFO - Negative
[2022-02-24 21:06:16,529] {sessions.py:161} WARNING - Retrying due to ConnectionError(ProtocolError('Connection aborted.', OSError(0, 'Error'))) status: GET https://oauth.reddit.com/r/doomer/new
[2022-02-24 21:08:35,931] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-02-24 21:10:21,049] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=get_reddit_data, execution_date=20220224T140000, start_date=20220224T200144, end_date=20220224T211018
