[2022-02-24 20:01:29,453] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T13:00:00+00:00 [queued]>
[2022-02-24 20:01:30,018] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T13:00:00+00:00 [queued]>
[2022-02-24 20:01:30,030] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:30,060] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:01:30,090] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:30,600] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_reddit_data> on 2022-02-24 13:00:00+00:00
[2022-02-24 20:01:30,747] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'get_reddit_data', 'scheduled__2022-02-24T13:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpiruimd1e', '--error-file', '/tmp/tmpv7rv2a3e']
[2022-02-24 20:01:30,770] {standard_task_runner.py:77} INFO - Job 46: Subtask get_reddit_data
[2022-02-24 20:01:30,709] {standard_task_runner.py:52} INFO - Started process 662 to run task
[2022-02-24 20:01:32,083] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T13:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 20:01:33,850] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=get_reddit_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T13:00:00+00:00
[2022-02-24 20:47:34,701] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2022-02-24 20:47:36,988] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 662. PIDs of all processes in the group: [662]
[2022-02-24 20:47:37,207] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 662
[2022-02-24 20:47:37,420] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-24 20:47:42,659] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 1, in <module>
    import train_data as train
  File "/opt/airflow/dags/train_data.py", line 238, in <module>
    x = training.train(custom_tweet)
  File "/opt/airflow/dags/train_data.py", line 140, in train
    negative_cleaned_tokens_list.append(self.cleaner.remove_noise(tokens, stop_words))
  File "/opt/airflow/dags/train_data.py", line 63, in remove_noise
    for token, tag in pos_tag(review_tokens):
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 166, in pos_tag
    return _pos_tag(tokens, tagset, tagger, lang)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 123, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 186, in tag
    features = self._get_features(i, word, context, prev, prev2)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 301, in _get_features
    add("i word", context[i])
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 289, in add
    def add(name, *args):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:47:45,609] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=get_reddit_data, execution_date=20220224T130000, start_date=20220224T200129, end_date=20220224T204745
[2022-02-24 20:47:48,179] {standard_task_runner.py:92} ERROR - Failed to execute job 46 for task get_reddit_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 1, in <module>
    import train_data as train
  File "/opt/airflow/dags/train_data.py", line 238, in <module>
    x = training.train(custom_tweet)
  File "/opt/airflow/dags/train_data.py", line 140, in train
    negative_cleaned_tokens_list.append(self.cleaner.remove_noise(tokens, stop_words))
  File "/opt/airflow/dags/train_data.py", line 63, in remove_noise
    for token, tag in pos_tag(review_tokens):
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 166, in pos_tag
    return _pos_tag(tokens, tagset, tagger, lang)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 123, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 186, in tag
    features = self._get_features(i, word, context, prev, prev2)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 301, in _get_features
    add("i word", context[i])
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 289, in add
    def add(name, *args):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:48:02,249] {process_utils.py:70} INFO - Process psutil.Process(pid=662, status='terminated', exitcode=1, started='20:01:30') (662) terminated with exit code 1
